apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lgtm-data-grafana
  labels:
    app: lgtm
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lgtm-data-prometheus
  labels:
    app: lgtm
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lgtm-data-loki
  labels:
    app: lgtm
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lgtm-data-tempo
  labels:
    app: lgtm
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
