apiVersion: v1
kind: Service
metadata:
  name: lgtm
  labels:
    app: lgtm
spec:
  type: ClusterIP
  ports:
    - port: 3001
      targetPort: 3000
      protocol: TCP
      name: grafana
    - port: 4317
      targetPort: 4317
      protocol: TCP
      name: otlp-grpc
    - port: 4318
      targetPort: 4318
      protocol: TCP
      name: otlp-http
  selector:
    app: lgtm
