import json
from google.genai import types

SRE_SYSTEM_PROMPT = """You are a diagnostic tool-use agent.
Your ONLY goal is to provide data from logs, metrics, and cluster state to the user.

DIAGNOSTIC HINTS:
- For cluster state (e.g., pod status, events), use Kubernetes tools (e.g., `kubectl_get`, `kubectl_describe`).
- To see all available apps in logs, use `list_loki_label_values(label='service_name')`.
- To check logs for a specific app, use `query_loki_logs(query='{service_name="node-typescript-app"}')`.
- To inspect source code or configurations, use GitHub tools (e.g., `search_repositories`, `get_file_contents`).

RULES:
1. SILENT INVESTIGATION: Do not narrate what you are about to do — just call tools.
2. If a tool fails (bad UID, bad query), solve it with another tool and RETRY immediately.
3. NEVER ask for permission in the middle of an investigation.
4. After gathering all necessary data, ALWAYS provide a clear final summary to the user.
5. Correlate cluster state with application telemetry.
6. NEVER suggest kubectl commands or any shell commands for the user to run. You have MCP tools — use them to complete the full investigation yourself. Never delegate work back to the user.

LOG EFFICIENCY RULES (MANDATORY):
1. ALWAYS pass `limit=50` when calling `query_loki_logs`.
2. ALWAYS pass `start` and `end` time parameters to scope logs to the relevant alert window.
3. Use LogQL line filters to pre-filter noise.
4. NEVER call the same log query twice in one investigation.
"""

class NativeTriageAgent:
    def __init__(self, client, model_name, tools):
        self.client = client
        self.model_name = model_name
        self.tools = tools
        self.tool_map = {t.name: t for t in tools}
        self.tool_declarations = [t.to_function_declaration() for t in tools]

    async def ainvoke(self, query: str) -> str:
        messages = [
            types.Content(
                role="user",
                parts=[types.Part.from_text(text=f"System Context:\n{SRE_SYSTEM_PROMPT}\n\nUser Query:\n{query}")]
            )
        ]
        
        # Max steps to prevent infinite loop
        for _ in range(15):
            config = types.GenerateContentConfig(
                temperature=0.1,
                tools=[types.Tool(function_declarations=self.tool_declarations)] if self.tool_declarations else None,
            )
            
            response = self.client.models.generate_content(
                model=self.model_name,
                contents=messages,
                config=config
            )
            
            if response.candidates:
                candidate = response.candidates[0]
                messages.append(candidate.content)
                
                # Check for function calls
                function_calls = []
                for part in candidate.content.parts:
                    if getattr(part, 'function_call', None):
                        function_calls.append(part.function_call)
                        
                if not function_calls:
                    # No more tool calls, we have our final text answer
                    return response.text or ""
                    
                # Execute tools
                function_responses = []
                for call in function_calls:
                    print(f"  [>] Calling tool: {call.name}")
                    tool_instance = self.tool_map.get(call.name)
                    if not tool_instance:
                        result = f"Error: Tool {call.name} not found"
                    else:
                        args = dict(call.args) if call.args else {}
                        result = await tool_instance.invoke(args)
                        
                    function_responses.append(
                        types.Part.from_function_response(
                            name=call.name,
                            response={"result": result}
                        )
                    )
                
                # Append tool responses to messages
                messages.append(
                    types.Content(
                        role="user", # The genai SDK specifies function responses come from 'user' or 'function' role depending on API versions, but usually 'user'
                        parts=function_responses
                    )
                )
            else:
                return "Error: No response generated by model."
                
        return "Agent stopped after reaching maximum steps."
